steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '$_IMAGE', '.']
images:
  - '$_IMAGE'
substitutions:
  _IMAGE: 'us-west1-docker.pkg.dev/$PROJECT_ID/tradewars-sol/tradewars-sol:$COMMIT_SHA'
